
import { Service, Booking } from './types';

export const SERVICES_DATA: Service[] = [
  {
    id: 1,
    title: 'Shuttle Ekspres Bandara',
    type: 'Shuttle',
    description: 'Layanan shuttle cepat, andal, dan nyaman antara Bandara Soekarno-Hatta dan lokasi-lokasi utama di Jakarta Pusat.',
    capacity: 12,
    image: 'https://picsum.photos/seed/shuttle1/400/400',
    facilities: ['Wi-Fi', 'AC', 'Ruang Bagasi'],
    priceOneWay: 150000,
    priceRoundTrip: 280000,
    availableDates: ['2024-09-10', '2024-09-11', '2024-09-12', '2024-09-13'],
    pickupPoints: ['Bandara T1', 'Bandara T2', 'Bandara T3'],
    dropOffPoints: ['Stasiun Gambir', 'Plaza Indonesia', 'Blok M Square'],
  },
  {
    id: 2,
    title: 'Tur Pribadi Keliling Kota',
    type: 'Private Tour',
    route: 'Tur Jakarta Pusat & Kota Tua',
    duration: '4 jam',
    price: 1200000,
    priceType: 'per kendaraan',
    capacity: 6,
    image: 'https://picsum.photos/seed/tour1/400/400',
    description: 'Jelajahi tengara ikonik Jakarta dengan kendaraan pribadi yang mewah dan pemandu wisata personal.',
    itinerary: ['Monumen Nasional', 'Kawasan Kota Tua', 'Pelabuhan Sunda Kelapa', 'Museum Fatahillah'],
    facilities: ['Pemandu Pribadi', 'Mobil SUV Mewah', 'Air Mineral', 'Jadwal Fleksibel'],
  },
  {
    id: 3,
    title: 'Shuttle Komuter Korporat',
    type: 'Shuttle',
    description: 'Layanan shuttle harian yang efisien untuk para profesional yang berkomuter antara Bekasi dan kawasan bisnis SCBD.',
    capacity: 25,
    image: 'https://picsum.photos/seed/shuttle2/400/400',
    facilities: ['Wi-Fi', 'Port Pengisian Daya', 'Kursi Nyaman'],
    priceOneWay: 50000,
    priceRoundTrip: 95000,
    availableDates: ['2024-09-10', '2024-09-11', '2024-09-12'],
    pickupPoints: ['Summarecon Mall Bekasi', 'Metropolitan Mall', 'Stasiun Bekasi'],
    dropOffPoints: ['Pacific Place', 'Equity Tower', 'Gedung Artha Graha'],
  },
  {
    id: 4,
    title: 'Tur Kebun Teh Puncak',
    type: 'Private Tour',
    route: 'Perjalanan Sehari dari Jakarta',
    duration: '8 jam',
    price: 1800000,
    priceType: 'per kendaraan',
    capacity: 5,
    image: 'https://picsum.photos/seed/tour2/400/400',
    description: 'Perjalanan sehari yang indah ke perkebunan teh di Puncak. Termasuk kunjungan dan makan siang di restoran lokal.',
    itinerary: ['Perkebunan Teh Gunung Mas', 'Makan Siang Khas Sunda', 'Taman Bunga Nusantara', 'Cimory Riverside'],
    facilities: ['Pemandu Ahli', 'Transportasi Pribadi', 'Camilan & Air Mineral'],
  },
];

export const BOOKINGS_DATA: Booking[] = [
    {
        id: 'BK-001',
        serviceTitle: 'Shuttle Ekspres Bandara',
        type: 'Shuttle',
        customerName: 'Budi Santoso',
        customerPhone: '6281234567890', 
        customerEmail: 'budi.s@email.com',
        bookingDate: '2024-09-10',
        status: 'Menunggu Konfirmasi',
        totalPrice: 150000,
        tripType: 'One Way',
        pickupPoint: 'Bandara T2',
        dropOffPoint: 'Stasiun Gambir',
    },
    {
        id: 'BK-002',
        serviceTitle: 'Tur Pribadi Keliling Kota',
        type: 'Private Tour',
        customerName: 'Citra Lestari',
        customerPhone: '6281298765432',
        bookingDate: '2024-08-16',
        status: 'Terkonfirmasi',
        totalPrice: 1200000,
    },
    {
        id: 'BK-003',
        serviceTitle: 'Shuttle Komuter Korporat',
        type: 'Shuttle',
        customerName: 'Andi Wijaya',
        customerPhone: '6281211223344',
        customerEmail: 'andi.w@corporate.com',
        bookingDate: '2024-09-11',
        status: 'Menunggu Konfirmasi',
        totalPrice: 95000,
        tripType: 'Round Trip'
    }
];